server:
  port: 8083

spring:
  application:
    name: lead-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/retailiq_lead}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: lead-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

customer:
  service:
    url: ${CUSTOMER_SERVICE_URL:http://localhost:8081}

segmentation:
  service:
    url: ${SEGMENTATION_SERVICE_URL:http://localhost:8082}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
