server:
  port: 8084

spring:
  application:
    name: campaign-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/retailiq_campaign}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

segmentation:
  service:
    url: ${SEGMENTATION_SERVICE_URL:http://localhost:8082}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
